// 
//  ListUsersDependency.swift
//  Messenger
//
//  Created by Canh Tran Wizeline on 3/9/20.
//  Copyright © 2020 CanhTran. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ListUsersDependency: ListUsersDependencyInterface {
    // MARK: - Module Setup

    func makeListUsersView() -> ViewInterface {
        let view = ListUsersViewController()

        let interactor = ListUsersInteractor()
        let navigationController = NavigationController()
        let router = ListUsersRouter(rootController: navigationController)
        router.setRootView(view, animated: false)

        let presenter = ListUsersPresenter(view: view, interactor: interactor, router: router)
        view.presenter = presenter

        return router.toController()
    }
}
