// 
//  ListUsersInterfaces.swift
//  Messenger
//
//  Created by Canh Tran Wizeline on 3/9/20.
//  Copyright © 2020 CanhTran. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

public protocol ListUsersDependencyInterface {
    func makeListUsersView() -> ViewInterface
}

public protocol ListUsersRouterInterface: NavigationRouterInterface {
}

public protocol ListUsersViewInterface: ViewInterface {
}

public protocol ListUsersPresenterInterface: PresenterInterface {
}

public protocol ListUsersInteractorInterface {
}
