// 
//  ListUsersPresenter.swift
//  Messenger
//
//  Created by Canh Tran Wizeline on 3/9/20.
//  Copyright © 2020 CanhTran. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ListUsersPresenter {
    // MARK: - Private Properties

    private unowned let view: ListUsersViewInterface
    private let interactor: ListUsersInteractorInterface
    private let router: ListUsersRouterInterface

    // MARK: - LifeCycle

    init(view: ListUsersViewInterface,
         interactor: ListUsersInteractorInterface,
         router: ListUsersRouterInterface) {
        self.view = view
        self.interactor = interactor
        self.router = router
    }

    func viewDidLoad() {
    }
}

// MARK: - ListUsersPresenterInterface

extension ListUsersPresenter: ListUsersPresenterInterface {
}
