// ___FILEHEADER___
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

// Dependency
public protocol ___VARIABLE_moduleName___DependencyInterface {
    func make___VARIABLE_moduleName___View() -> ViewInterface
}

// Router
public protocol ___VARIABLE_moduleName___RouterInterface: NavigationRouterInterface {
}

// ViewController
public protocol ___VARIABLE_moduleName___ViewInterface: ViewInterface {
}

// Presenter
public protocol ___VARIABLE_moduleName___PresenterInterface: PresenterInterface {
}

// Interactor
public protocol ___VARIABLE_moduleName___InteractorInterface {
}
